FROM node:14-alpine

ENV NODE_ENV production

WORKDIR /app

RUN npm i -g \
        prettier \
        eslint@^7 \
        react@^16.8 \
        react-dom@^16.8 \
        react-scripts@^3.0 \
        typescript@>=2.8.0 \
        eslint-config-react-app \
        eslint-config-prettier \
        eslint-plugin-import \
        eslint-plugin-jsx-a11y \
        eslint-plugin-react \
        eslint-plugin-flowtype@2.x \
        babel-eslint \
        eslint-plugin-react-hooks
